# Generated by Django 5.0.7 on 2026-09-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Leave blank to apply to all devices of device_type.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alertrule'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['organization', '-triggered_at'], name='alerts_aler_organiz_794696_idx'),
        ),
    ]
