# Generated by Django 5.0.7 on 2026-09-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('value_numeric', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_readings', to='accounts.organization')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', 'metric_key', '-recorded_at'], name='telemetry_t_device__4df817_idx'), models.Index(fields=['organization', '-recorded_at'], name='telemetry_t_organiz_77490d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('bucket_start', models.DateTimeField()),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('sample_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_rollups', to='accounts.organization')),
            ],
            options={
                'ordering': ['-bucket_start'],
                'indexes': [models.Index(fields=['organization', '-bucket_start'], name='telemetry_t_organiz_77f5cc_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='telemetryrollup',
            constraint=models.UniqueConstraint(fields=('device', 'metric_key', 'bucket_start'), name='unique_rollup_bucket'),
        ),
    ]
