# Generated by Django 5.0.7 on 2026-09-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('sites_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites_app.site'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='metricdefinition',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_device_type_name_per_org'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['mqtt_topic'], name='devices_dev_mqtt_to_604c78_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='devices_dev_organiz_c0273e_idx'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'device_id'), name='unique_device_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('device_type', 'key'), name='unique_metric_key_per_device_type'),
        ),
    ]
